# Site settings
title: Simmons Consult International
email: hello@simmonsconsult.co
description: > # this means to ignore newlines until "baseurl:"
  - Simmons Consult International is committed to provide holistic innovations and greener solutions that empower the client to be eco-friendly, environmentally compliant and geared towards sustainable business.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://simmonsconsult.co" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
